
package tr.gov.nvi.kpsv2.ws.kisisorgulatckimlikno;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "KisiSorgulaTCKimlikNoServis", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KisiSorgulaTCKimlikNoServis {


    /**
     * 
     * @param kriterListesi
     * @return
     *     returns tr.gov.nvi.kpsv2.ws.kisisorgulatckimlikno.KisiBilgisiSonucu
     */
    @WebMethod(operationName = "ListeleCoklu", action = "http://kps.nvi.gov.tr/2011/01/01/KisiSorgulaTCKimlikNoServis/ListeleCoklu")
    @WebResult(name = "ListeleCokluResult", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
    @RequestWrapper(localName = "ListeleCoklu", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.kisisorgulatckimlikno.ListeleCoklu")
    @ResponseWrapper(localName = "ListeleCokluResponse", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.kisisorgulatckimlikno.ListeleCokluResponse")
    public KisiBilgisiSonucu listeleCoklu(
        @WebParam(name = "kriterListesi", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
        ArrayOfKisiSorgulaTCKimlikNoSorguKriteri kriterListesi);

}
