
package tr.gov.nvi.kpsv2.ws.aksokutumil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AksOkuTumIlServis", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AksOkuTumIlServis {


    /**
     * 
     * @param kriter
     * @return
     *     returns tr.gov.nvi.kpsv2.ws.aksokutumil.IlSonucu
     */
    @WebMethod(operationName = "Listele", action = "http://kps.nvi.gov.tr/2011/01/01/AksOkuTumIlServis/Listele")
    @WebResult(name = "ListeleResult", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
    @RequestWrapper(localName = "Listele", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.aksokutumil.Listele")
    @ResponseWrapper(localName = "ListeleResponse", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.aksokutumil.ListeleResponse")
    public IlSonucu listele(
        @WebParam(name = "kriter", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
        AksOkuTumIlSorguKriteri kriter);

}
