
package tr.gov.nvi.kpsv2.ws.aksokutumilebagliilce;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AksOkuTumIleBagliIlceServis", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", wsdlLocation = "/tr/gov/nvi/kpsv2/ws/wsdl/AksOkuTumIleBagliIlceServis.wsdl")
public class AksOkuTumIleBagliIlceServis_Service
    extends Service
{

    private final static URL AKSOKUTUMILEBAGLIILCESERVIS_WSDL_LOCATION;
    private final static WebServiceException AKSOKUTUMILEBAGLIILCESERVIS_EXCEPTION;
    private final static QName AKSOKUTUMILEBAGLIILCESERVIS_QNAME = new QName("http://kps.nvi.gov.tr/2011/01/01", "AksOkuTumIleBagliIlceServis");

    static {
        AKSOKUTUMILEBAGLIILCESERVIS_WSDL_LOCATION = tr.gov.nvi.kpsv2.ws.aksokutumilebagliilce.AksOkuTumIleBagliIlceServis_Service.class.getResource("/tr/gov/nvi/kpsv2/ws/wsdl/AksOkuTumIleBagliIlceServis.wsdl");
        WebServiceException e = null;
        if (AKSOKUTUMILEBAGLIILCESERVIS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/tr/gov/nvi/kpsv2/ws/wsdl/AksOkuTumIleBagliIlceServis.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        AKSOKUTUMILEBAGLIILCESERVIS_EXCEPTION = e;
    }

    public AksOkuTumIleBagliIlceServis_Service() {
        super(__getWsdlLocation(), AKSOKUTUMILEBAGLIILCESERVIS_QNAME);
    }

    public AksOkuTumIleBagliIlceServis_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AksOkuTumIleBagliIlceServis
     */
    @WebEndpoint(name = "CustomBinding_AksOkuTumIleBagliIlceServis")
    public AksOkuTumIleBagliIlceServis getCustomBindingAksOkuTumIleBagliIlceServis() {
        return super.getPort(new QName("http://kps.nvi.gov.tr/2011/01/01", "CustomBinding_AksOkuTumIleBagliIlceServis"), AksOkuTumIleBagliIlceServis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AksOkuTumIleBagliIlceServis
     */
    @WebEndpoint(name = "CustomBinding_AksOkuTumIleBagliIlceServis")
    public AksOkuTumIleBagliIlceServis getCustomBindingAksOkuTumIleBagliIlceServis(WebServiceFeature... features) {
        return super.getPort(new QName("http://kps.nvi.gov.tr/2011/01/01", "CustomBinding_AksOkuTumIleBagliIlceServis"), AksOkuTumIleBagliIlceServis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AKSOKUTUMILEBAGLIILCESERVIS_EXCEPTION!= null) {
            throw AKSOKUTUMILEBAGLIILCESERVIS_EXCEPTION;
        }
        return AKSOKUTUMILEBAGLIILCESERVIS_WSDL_LOCATION;
    }

}
