
package tr.gov.nvi.kpsv2.ws.kisilistele;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "KisiListeleServis", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KisiListeleServis {


    /**
     * 
     * @param kriter
     * @return
     *     returns tr.gov.nvi.kpsv2.ws.kisilistele.KisiListesiSonucu
     */
    @WebMethod(operationName = "Sayfala", action = "http://kps.nvi.gov.tr/2011/01/01/KisiListeleServis/Sayfala")
    @WebResult(name = "SayfalaResult", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
    @RequestWrapper(localName = "Sayfala", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.kisilistele.Sayfala")
    @ResponseWrapper(localName = "SayfalaResponse", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01", className = "tr.gov.nvi.kpsv2.ws.kisilistele.SayfalaResponse")
    public KisiListesiSonucu sayfala(
        @WebParam(name = "kriter", targetNamespace = "http://kps.nvi.gov.tr/2011/01/01")
        KisiListeleSorguKriteri kriter);

}
