<?xml version="1.0" encoding="utf-8"?><wsdl:definitions name="AksOkuTumIlServis" targetNamespace="http://kps.nvi.gov.tr/2011/01/01" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://kps.nvi.gov.tr/2011/01/01" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa10="http://www.w3.org/2005/08/addressing">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://kps.nvi.gov.tr/2011/01/01">
      <xsd:element name="Listele">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="kriter" nillable="true" type="tns:AksOkuTumIlSorguKriteri" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:complexType name="AksOkuTumIlSorguKriteri">
        <xsd:sequence />
      </xsd:complexType>
      <xsd:element name="AksOkuTumIlSorguKriteri" nillable="true" type="tns:AksOkuTumIlSorguKriteri" />
      <xsd:element name="ListeleResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="ListeleResult" nillable="true" type="tns:IlSonucu" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:complexType name="IlSonucu">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="HataBilgisi" nillable="true" type="tns:Parametre" />
          <xsd:element minOccurs="0" name="SorguSonucu" nillable="true" type="tns:ArrayOfIl" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="IlSonucu" nillable="true" type="tns:IlSonucu" />
      <xsd:complexType name="Parametre">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="Aciklama" nillable="true" type="xsd:string" />
          <xsd:element minOccurs="0" name="Kod" nillable="true" type="xsd:int" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="Parametre" nillable="true" type="tns:Parametre" />
      <xsd:complexType name="ArrayOfIl">
        <xsd:sequence>
          <xsd:element minOccurs="0" maxOccurs="unbounded" name="Il" nillable="true" type="tns:Il" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="ArrayOfIl" nillable="true" type="tns:ArrayOfIl" />
      <xsd:complexType name="Il">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="Ad" nillable="true" type="xsd:string" />
          <xsd:element minOccurs="0" name="HataBilgisi" nillable="true" type="tns:Parametre" />
          <xsd:element minOccurs="0" name="Kod" nillable="true" type="xsd:int" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="Il" nillable="true" type="tns:Il" />
    </xsd:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="AksOkuTumIlServis_Listele_InputMessage">
    <wsdl:part name="parameters" element="tns:Listele" />
  </wsdl:message>
  <wsdl:message name="AksOkuTumIlServis_Listele_OutputMessage">
    <wsdl:part name="parameters" element="tns:ListeleResponse" />
  </wsdl:message>
  <wsdl:portType name="AksOkuTumIlServis">
    <wsdl:operation name="Listele">
      <wsdl:input wsaw:Action="http://kps.nvi.gov.tr/2011/01/01/AksOkuTumIlServis/Listele" message="tns:AksOkuTumIlServis_Listele_InputMessage" />
      <wsdl:output wsaw:Action="http://kps.nvi.gov.tr/2011/01/01/AksOkuTumIlServis/ListeleResponse" message="tns:AksOkuTumIlServis_Listele_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CustomBinding_AksOkuTumIlServis" type="tns:AksOkuTumIlServis">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Listele">
      <soap12:operation soapAction="http://kps.nvi.gov.tr/2011/01/01/AksOkuTumIlServis/Listele" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AksOkuTumIlServis">
    <wsdl:port name="CustomBinding_AksOkuTumIlServis" binding="tns:CustomBinding_AksOkuTumIlServis">
      <soap12:address location="https://kpsv2test.nvi.gov.tr/Services/RoutingService.svc" />
      <wsa10:EndpointReference>
        <wsa10:Address>https://kpsv2test.nvi.gov.tr/Services/RoutingService.svc</wsa10:Address>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>